format = "$status$battery$username$hostname $localip$container$directory$git_branch$git_status$git_state$character"
add_newline = false

[status]
disabled = false
format = '[\[$symbol $int\]]($style) '

[[battery.display]]
threshold = 40

[username]
disabled = false
show_always = true
style_user = "green"
format ="[$user]($style)"

[hostname]
ssh_only = false
format = "[@](dimmed)[$hostname]($style)"
style = "bright-purple"
trim_at = "."
disabled = false

[localip]
ssh_only = true
disabled = false

[container]
symbol = "ğŸ"
format = "[$symbol ](style)"

[directory]
truncation_length = 80
truncation_symbol = "â€¦/"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
