format = "$status$battery$container$localip[î‚¶](blue)$username$hostname[ î‚± ](fg:black bg:blue)[$directory](bg:blue)[î‚´](blue)$git_branch$git_status$git_state$character"
add_newline = false

[status]
disabled = false
format = '[\[$symbol $int\]]($style) '

[[battery.display]]
threshold = 40

[username]
disabled = false
show_always = true
style_user = "fg:bright-white bg:blue"
style_root = "fg:bright-white bg:red"
format ="[$user]($style)"

[hostname]
ssh_only = false
format = "[[@](dimmed bg:blue)$hostname]($style)"
style = "fg:bright-white bg:blue"
trim_at = "."
disabled = false

[localip]
ssh_only = true
disabled = false
#style = "fg:black bg:bright-yellow"
#format = "[î‚¶](bright-yellow)[$localipv4]($style)[î‚´](bright-yellow) "
format = "ğŸŒ "

[container]
symbol = "ğŸ"
format = "[$symbol ](style)"

[directory]
truncation_length = 80
truncation_symbol = "â€¦/"
style = "fg:bright-cyan bg:blue"
read_only_style = "bg:blue"
[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
